# generated by Norcroft CLIPPER C 3.18A Mar 13 1989 at 08:43:49
# r0 EQU 0
# r1 EQU 1
# r2 EQU 2
# r3 EQU 3
# r4 EQU 4
# r5 EQU 5
# r6 EQU 6
# r7 EQU 7
# r8 EQU 8
# r9 EQU 9
# r10 EQU 10
# r11 EQU 11
# r12 EQU 12
# r13 EQU 13
# r14 EQU 14
# sp EQU 15
#
# f0 EQU 0
# f1 EQU 1
# f2 EQU 2
# f3 EQU 3
# f4 EQU 4
# f5 EQU 5
# f6 EQU 6
# f7 EQU 7
#
 .text
#
#
___codeseg:
 .align 4
#
#
 .byte 'c','r','e','a'
 .byte 't','e','_','t'
 .byte 'h','r','e','a'
 .byte 'd',0,0,0
 .long 0xff000010
 .align 4
#
#
_stack_switch_and_go:
 movw	r0,r3		# Pick up the stack base
 movw	r3,sp		# Set the stack pointer
 b	(r1)		# enter the rest.
 .align 4
#
 .data
#
___dataseg:
#
 .globl _stack_switch_and_go
#
# .extern _nil
# .extern __fprintf
# .extern __iob
#
# END
