/* A lexical scanner generated by flex */

/* scanner skeleton version:
 * $Header: /a_mount/brad/denton_export/denton/You/NewYou/Src/RCS/feelflex.skl,v 1.2 1994/01/25 16:54:37 djb Exp $
 *
 * Mucked about with for feel...
 */

#define FLEX_SCANNER

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <osfcn.h>

/* use prototypes in function declarations */
#define YY_USE_PROTOS

/* the "const" storage-class-modifier is valid */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#ifdef __GNUCXX__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
#else
#include <stdlib.h>
#endif	/* __GNUC__ */

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#define const
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
/* we can't get here if it's an ANSI C compiler, or a C++ compiler,
 * so it's got to be a K&R compiler, and therefore there's no standard
 * place from which to include these definitions
 */
char *malloc();
int free();
int read();
#endif


/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* returned upon end-of-file */
#define YY_END_TOK 0

/* copy whatever the last rule matched to the standard output */

/* cast to (char *) is because for 8-bit chars, yytext is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yytext, yyleng, 1, yyout )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yyin), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );
#define YY_NULL 0

/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 * 	if ( something_happens )
 *		YY_FATAL_ERROR( "oops, the something happened" );
 *	else
 *		everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, stderr ); \
		(void) putc( '\n', stderr ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1

/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* special action meaning "start processing a new file" */
#define YY_NEW_FILE \
	do \
		{ \
		yy_init_buffer( yy_current_buffer, yyin ); \
		yy_load_buffer_state(); \
		} \
	while ( 0 )

/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void)) 

/* code executed at the end of each rule */
#define YY_BREAK break;

#define YY_END_OF_BUFFER_CHAR 0

#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) /* size of default input buffer */
#endif

typedef struct yy_buffer_state *YY_BUFFER_STATE;

#define YY_CHAR char
# line 1 "feelflex.lex"
#define INITIAL 0
/* -*- C -*- */
/* EuLisp lexer
 *
 * Russell Bradford, Bath 1990
 * Based on work by J. Bejar, A. Moreno, E. Sesa (FIB,UPC) - Bath, July 1990
 *
 */
/* $Id: feelflex.lex,v 1.2 1994/01/25 16:54:37 djb Exp $ */
/* $Log:
*/
# line 14 "feelflex.lex"

#include "defs.h"
/* We need to add an extra parameter */
#ifdef YY_DECL
#undef YY_DECL
#ifdef YY_USE_PROTOS
#define YY_DECL  int yylex YY_PROTO((LispObject *stacktop))
#else
#define YY_DECL  int yylex (stacktop) LispObject *stacktop;
#endif
#endif
/* Emergency fileno */

#ifndef HAS_READFILENO
#define fileno(fh) (fh == stdin ? 0 \
		    : (fh == stdout ? 1 \
                       : (fh == stderr ? 2 : 3)))
#endif /* HAS_READFILENO */

#include <string.h>
#include <ctype.h>
#include "defs.h"
#include "structs.h"
#include "funcalls.h"
#include "global.h"
#include "symboot.h"
#include "error.h"

#include "lex_global.h"

#ifdef __STDC__
#define OF(ansi, kr, krargs) ansi
#define PROTO(args) args
#else
#define OF(ansi, kr, krargs) kr krargs
#define PROTO(args) ()
#endif

#ifdef __STDC__

/*
#ifndef DONT_HAVE_STDLIB_H
#include <stdlib.h>
#else
void *malloc( unsigned );
void free( void* );
#endif
*/

extern int read(int, char *, unsigned);

#endif

/* the values returned */
double flex_floatval;
long flex_ratnumval, flex_ratdenval;
long flex_intval;
char flex_charval;
char flex_stringval[1024];	/* I don't like fixed array sizes */
char flex_idval[256];
pptoken pptok;			/* for backward compatibility */
int lex_input_line_number=1;	/* Needs changing for shared memory */

static double convert_float PROTO((void));
static long convert_integer PROTO((char *, int));
static long int_with_base PROTO((char *, int *));
static void convert_rational PROTO((void));
static void convert_string PROTO((LispObject *stacktop));
static char convert_character PROTO((void));
static void tidy_id PROTO((void));
int escaped_id PROTO((char*));
char *visible PROTO((char));

/* Hack the lex reader */

#ifdef YY_INPUT
#undef YY_INPUT
#endif

#ifdef HAS_READFILENO
#define YY_INPUT(buf,result,max_size) \
  if ( (result = system_read(stacktop, fileno(yyin), \
			     (char *) buf, max_size )) < 1 ) \
    { 						\
      if(result == 0)\
	GC_sync_test();\
      else{  \
	perror("Some very bad thing happened");\
        system_lisp_exit(0);					\
	}\
    }			
#else
#define YY_INPUT(buf,result,max_size) \
{ 					\
  int len;				\
  char *ret;				\
  fprintf(stderr,"Reading from: %d %d\n",buf,max_size);	\
  if (fgets(buf,max_size,yyin)==NULL)			\
    result=0;				\
  else					\
    result=strlen(buf);			\
}

#endif /* HAS_READFILENO */

/* forward references */
/* tokens */
/*delimeter	{whitespace}|{pair-begin}|{pair-end}|{string-begin}|{string-end}|{comment-begin}*/
/* number syntax */
/* integers */
/* rationals */
/* floats */
/* strings */
/* we do these by hand, as it's easier that way */
/* character syntax */
/*special-name	alert|backspace|delete|formfeed|linefeed|newline|return|tab|space|vertical-tab*/
/* identifiers */
/* Scheme support */
# line 237 "feelflex.lex"

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yytext
 */
#define YY_DO_BEFORE_ACTION \
	yytext = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yytext */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext )


struct yy_buffer_state
    {
    FILE *yy_input_file;

    YY_CHAR *yy_ch_buf;		/* input buffer */
    YY_CHAR *yy_buf_pos;	/* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters*/
    int yy_buf_size;	

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;		/* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

static YY_BUFFER_STATE yy_current_buffer;

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed */
static YY_CHAR yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */



#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

extern YY_CHAR *yytext;
extern int yyleng;
extern FILE *yyin, *yyout;

YY_CHAR *yytext;
int yyleng;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

#define YY_END_OF_BUFFER 27
typedef int yy_state_type;
static const short int yy_accept[170] =
    {   0,
        0,    0,   27,   25,    3,    3,   22,   19,   11,    7,
        5,    6,   22,    9,    4,   16,   25,   25,    8,   25,
       22,    0,    0,    0,    0,   24,    0,   23,    0,    0,
       22,    0,   22,   16,    0,    0,   10,   22,   12,    0,
        0,   12,    0,    0,    0,    2,   22,    0,    0,   22,
        0,    0,    0,   14,   15,   17,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   22,
        0,    0,   12,   22,    0,    0,   22,    0,    0,    0,
       22,    0,    0,   12,    0,    0,   13,    0,   12,   18,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

       21,   21,   20,   22,    0,    0,   22,   22,    0,    0,
        0,   12,    0,   12,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   21,    0,   21,   22,
       12,    0,   13,   13,   13,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   21,   13,    0,    0,    0,    0,
        0,    0,    0,   21,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0
    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    5,    5,    5,    8,    9,
       10,    5,   11,   12,   13,   14,   15,   16,   16,   17,
       17,   17,   17,   17,   17,   18,   18,    5,   19,    5,
        5,    5,    5,   20,   21,   22,   23,   24,   25,   26,
       27,   27,   28,   27,   29,   30,   31,   32,   33,   34,
       27,   35,   36,   37,   38,   39,   40,   41,   27,   27,
        5,   42,    5,   43,    5,   44,   21,   22,   23,   24,

       25,   26,   27,   27,   28,   27,   29,   30,   31,   32,
       33,   34,   27,   35,   36,   37,   38,   39,   40,   41,
       27,   27,    5,   45,    5,    5,    1
    } ;

static const YY_CHAR yy_meta[46] =
    {   0,
        1,    1,    1,    1,    2,    1,    3,    1,    1,    1,
        2,    1,    2,    2,    2,    4,    4,    4,    1,    2,
        4,    4,    4,    4,    4,    4,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    2,    2,    1,    2
    } ;

static const short int yy_base[198] =
    {   0,
        0,    0,  414,  415,  415,  415,    4,  415,   34,  415,
      415,  415,   70,  393,   37,  102,  409,    0,  415,   16,
       17,    0,   21,   56,  395,  415,   31,  415,    0,  107,
       23,   80,   90,    0,    0,   36,  415,   38,   76,    0,
       69,  135,  138,  150,  407,  415,   80,   96,    0,  120,
      127,    0,    0,   54,   88,  394,  415,  378,  386,  381,
      372,  376,  378,  377,  367,  379,  374,    0,  171,  134,
        0,  135,  165,  142,  143,    0,  149,    0,  150,  185,
      155,  163,    0,  195,  205,  208,  211,  215,  218,  383,
      372,  373,  365,  359,  361,  352,  354,  369,  367,  353,

        0,  415,  415,  164,  172,    0,  239,  195,  197,    0,
      227,  230,  242,  245,  248,  371,   73,    0,  351,  356,
      359,  311,  303,  264,  248,  259,  415,  243,    0,  123,
      136,    0,  263,   93,    0,  241,  241,  239,  249,  248,
      245,  237,  246,  242,    0,    0,  235,  243,  242,  229,
      221,  219,  215,  415,  194,  179,  174,  168,  165,  155,
      147,  146,  134,  133,  144,  103,  109,  102,  415,  283,
      287,  291,  296,  301,  306,  311,  316,  119,  321,  325,
      330,  335,  339,  344,  349,  351,   95,  356,  361,  366,
      371,  376,   91,   81,   60,  378,   53

    } ;

static const short int yy_def[198] =
    {   0,
      169,    1,  169,  169,  169,  169,  170,  169,  169,  169,
      169,  169,  171,  169,  172,  169,  173,  174,  169,  175,
      170,  176,  177,  169,  169,  169,  169,  169,  178,  179,
      180,  169,  180,   16,  181,  182,  169,  183,  169,  184,
      185,  169,  169,  169,  173,  169,  170,  175,  175,  170,
      177,  177,  186,  169,  169,  178,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  187,  188,  180,
      189,  190,  180,  180,  182,  182,  183,  191,  192,  169,
      183,  185,  185,  169,  169,  169,  169,  169,  169,  186,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,

      193,  169,  169,  180,  190,  190,  180,  183,  192,  192,
      169,  169,  169,  169,  169,  169,  169,  194,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  195,  107,
      107,  196,  169,  169,  194,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  197,  196,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,    0,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169

    } ;

static const short int yy_nxt[461] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   13,   15,    7,   16,   16,   16,   17,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,   18,    7,   19,   20,   22,   55,   55,   23,   24,
       24,   24,   39,   39,   39,   25,  154,   49,   22,   26,
       47,   23,   52,  145,   71,   50,   27,   72,   43,   54,
       28,   24,   24,   24,   29,   30,   32,   76,   40,   78,
       74,   41,   79,   33,  135,   34,   34,   34,  134,  134,
       53,   39,   39,   39,  129,   24,   24,   24,  101,   80,

       80,   25,   43,   55,   55,   73,   73,   73,  134,  134,
       83,   35,   27,   81,   36,   42,   43,   34,   34,   34,
       29,   22,   56,  127,   23,   44,   44,   58,   59,  168,
       60,   71,   61,   70,   72,   70,   62,   49,   63,  167,
       47,   64,   65,   66,   86,   67,   70,   68,   70,   69,
       84,   84,   84,   87,   87,   87,  166,  127,   85,   85,
       88,   22,   88,  165,   23,   89,   89,   89,   52,  127,
      127,   50,  103,  103,  103,   71,  106,  164,   72,  104,
       73,   73,   73,   71,   76,  163,   72,   74,  107,  107,
       78,  110,  127,   79,  108,  111,   78,  111,  162,   79,

      112,  112,  112,  161,   83,   71,   71,   81,   72,   72,
       84,   84,   84,  106,  160,  113,  104,  113,   85,   85,
      114,  114,  114,  115,  115,  115,   87,   87,   87,  116,
       89,   89,   89,   89,   89,   89,   78,  159,  110,   79,
      117,  108,  112,  112,  112,  112,  112,  112,  118,  130,
      127,  130,  158,  157,  131,  131,  131,  114,  114,  114,
      114,  114,  114,  115,  115,  115,  156,  127,  155,  153,
      127,  152,  151,  150,  149,  148,  147,  127,  133,  144,
       71,  143,  132,   72,   21,  142,   21,   21,   31,   31,
       31,   31,   38,  141,   38,   38,   45,   45,   45,   45,

       45,   47,   47,   47,   47,   47,   48,   48,   48,   48,
       48,   50,   50,   50,   50,   50,   51,   51,   51,   51,
       51,   57,   57,   57,   57,   57,   70,  140,   70,   70,
       74,   74,   74,   74,   74,   75,   75,   75,   75,   75,
       77,  139,   77,   77,   81,   81,   81,   81,   81,   82,
       82,   82,   82,   82,   90,   90,  102,  102,  102,  102,
      102,  104,  104,  104,  104,  104,  105,  105,  105,  105,
      105,  108,  108,  108,  108,  108,  109,  109,  109,  109,
      109,  146,  146,  138,  137,  136,  133,  128,  127,  126,
      125,  124,  123,  122,  121,  120,  119,   43,  100,   99,

       98,   97,   96,   95,   94,   93,   92,   91,   43,   46,
       54,   46,   37,  169,    3,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169
    } ;

static const short int yy_chk[461] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    7,   27,   27,    7,    9,
        9,    9,   15,   15,   15,    9,  197,   20,   21,    9,
       20,   21,   23,  195,   31,   23,    9,   31,   54,   54,
        9,   24,   24,   24,    9,    9,   13,   36,   15,   38,
       36,   15,   38,   13,  194,   13,   13,   13,  117,  117,
       24,   39,   39,   39,  193,   32,   32,   32,  187,   39,

       39,   32,   55,   55,   55,   33,   33,   33,  134,  134,
       41,   13,   32,   41,   13,   16,   16,   16,   16,   16,
       32,   47,  178,  168,   47,   16,   16,   30,   30,  167,
       30,   33,   30,  130,   33,  130,   30,   48,   30,  166,
       48,   30,   30,   30,   43,   30,  131,   30,  131,   30,
       42,   42,   42,   43,   43,   43,  165,  164,   42,   42,
       44,   50,   44,  163,   50,   44,   44,   44,   51,  162,
      161,   51,   69,   69,   69,   70,   72,  160,   70,   72,
       73,   73,   73,   74,   75,  159,   74,   75,   73,   73,
       77,   79,  158,   77,   79,   80,   81,   80,  157,   81,

       80,   80,   80,  156,   82,  104,   73,   82,  104,   73,
       84,   84,   84,  105,  155,   85,  105,   85,   84,   84,
       85,   85,   85,   86,   86,   86,   87,   87,   87,   86,
       88,   88,   88,   89,   89,   89,  108,  153,  109,  108,
       86,  109,  111,  111,  111,  112,  112,  112,   86,  107,
      152,  107,  151,  150,  107,  107,  107,  113,  113,  113,
      114,  114,  114,  115,  115,  115,  149,  148,  147,  144,
      143,  142,  141,  140,  139,  138,  137,  136,  133,  128,
      107,  126,  115,  107,  170,  125,  170,  170,  171,  171,
      171,  171,  172,  124,  172,  172,  173,  173,  173,  173,

      173,  174,  174,  174,  174,  174,  175,  175,  175,  175,
      175,  176,  176,  176,  176,  176,  177,  177,  177,  177,
      177,  179,  179,  179,  179,  179,  180,  123,  180,  180,
      181,  181,  181,  181,  181,  182,  182,  182,  182,  182,
      183,  122,  183,  183,  184,  184,  184,  184,  184,  185,
      185,  185,  185,  185,  186,  186,  188,  188,  188,  188,
      188,  189,  189,  189,  189,  189,  190,  190,  190,  190,
      190,  191,  191,  191,  191,  191,  192,  192,  192,  192,
      192,  196,  196,  121,  120,  119,  116,  100,   99,   98,
       97,   96,   95,   94,   93,   92,   91,   90,   67,   66,

       65,   64,   63,   62,   61,   60,   59,   58,   56,   45,
       25,   17,   14,    3,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0

/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_CHAR *yy_c_buf_p = (YY_CHAR *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO((LispObject *));
static void yyunput YY_PROTO(( YY_CHAR c, YY_CHAR *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( LispObject *,FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

#define yy_new_buffer yy_create_buffer

#ifdef __cplusplus
static int yyinput YY_PROTO(( void))
#else
static int input YY_PROTO((LispObject *));
#endif

YY_DECL
    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp, *yy_bp;
    register int yy_act;




    if ( yy_init )
	{
	YY_USER_INIT;

	if ( ! yy_start )
	    yy_start = 1;	/* first start state */

	if ( ! yyin )
	    yyin = stdin;

	if ( ! yyout )
	    yyout = stdout;

	if ( yy_current_buffer )
	    yy_init_buffer( yy_current_buffer, yyin );
	else
	    yy_current_buffer = yy_create_buffer(stacktop, yyin, YY_BUF_SIZE );

	yy_load_buffer_state();

	yy_init = 0;
	}

    while ( 1 )		/* loops until end-of-file is reached */
	{
	yy_cp = yy_c_buf_p;

	/* support of yytext */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

	yy_current_state = yy_start;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 170 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_base[yy_current_state] != 415 );

yy_find_action:
	yy_act = yy_accept[yy_current_state];

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:	/* this label is used only to access EOF actions */


	switch ( yy_act )
	    {
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case YY_STATE_EOF(INITIAL):
# line 239 "feelflex.lex"
{ return(END_OF_STREAM); }
	YY_BREAK
case 2:
# line 241 "feelflex.lex"
{lex_input_line_number++;}
	YY_BREAK
case 3:
# line 243 "feelflex.lex"
{if (yytext[0]=='\n') lex_input_line_number++;}
	YY_BREAK
case 4:
# line 245 "feelflex.lex"
{ return(DOT); }
	YY_BREAK
case 5:
# line 247 "feelflex.lex"
{ return(OPEN_PAIR); }
	YY_BREAK
case 6:
# line 249 "feelflex.lex"
{ return(CLOSE_PAIR); }
	YY_BREAK
case 7:
# line 251 "feelflex.lex"
{
                  pptok.lispval=get_symbol(stacktop,"quote");
		  return(WRAPPER);
		}
	YY_BREAK
case 8:
# line 256 "feelflex.lex"
{ 
                  pptok.lispval=get_symbol(stacktop,"quasiquote");
		  return(WRAPPER);
		}
	YY_BREAK
case 9:
# line 261 "feelflex.lex"
{ pptok.lispval=get_symbol(stacktop,"unquote");
		  return(WRAPPER);
		}
	YY_BREAK
case 10:
# line 265 "feelflex.lex"
{ pptok.lispval=get_symbol(stacktop,"unquote-splicing");
		  return(WRAPPER);
		}
	YY_BREAK
case 11:
# line 269 "feelflex.lex"
{ return(EXTENSION); }
	YY_BREAK
case 12:
# line 271 "feelflex.lex"
{ flex_floatval = convert_float();
		  pptok.lispval = allocate_float(stacktop,flex_floatval);
		  return(FLOAT); }
	YY_BREAK
case 13:
# line 275 "feelflex.lex"
{ convert_rational(); /* XXX: ?? */
		  return(RATIONAL); }
	YY_BREAK
case 14:
# line 278 "feelflex.lex"
{ flex_intval = convert_integer(yytext, 2);
		  pptok.lispval = allocate_integer(stacktop,flex_intval);
		  return(INTEGER); }
	YY_BREAK
case 15:
# line 282 "feelflex.lex"
{ flex_intval = convert_integer(yytext, 8);
		  pptok.lispval = allocate_integer(stacktop,flex_intval);
		  return(INTEGER); }
	YY_BREAK
case 16:
# line 286 "feelflex.lex"
{ flex_intval = atol(yytext);
		  pptok.lispval = allocate_integer(stacktop,flex_intval);
		  return(INTEGER); }
	YY_BREAK
case 17:
# line 290 "feelflex.lex"
{ flex_intval = convert_integer(yytext, 16);
		  pptok.lispval = allocate_integer(stacktop,flex_intval);
		  return(INTEGER); }
	YY_BREAK
case 18:
# line 294 "feelflex.lex"
{ int returns;
			  flex_intval = int_with_base(yytext, &returns);
			  if (returns != yyleng) yyless(returns);
			  pptok.lispval = allocate_integer(stacktop,flex_intval);
			  return(INTEGER); }
	YY_BREAK
case 19:
# line 300 "feelflex.lex"
{ convert_string(stacktop);
		  pptok.lispval = allocate_string(stacktop,flex_stringval,
						     strlen(flex_stringval));
		  return(STRING); }
	YY_BREAK
case 20:
# line 305 "feelflex.lex"
{ flex_charval = '^';
                  pptok.lispval = allocate_char(stacktop,flex_charval);
                  return(CHARACTER); }
	YY_BREAK
case 21:
# line 309 "feelflex.lex"
{ flex_charval = convert_character();
		  pptok.lispval = allocate_char(stacktop,flex_charval);
		  return(CHARACTER); }
	YY_BREAK
case 22:
# line 313 "feelflex.lex"
{ tidy_id();
		  pptok.lispval = get_symbol(stacktop,flex_idval);
		  return(IDENTIFIER); }
	YY_BREAK
case 23:
# line 317 "feelflex.lex"
{ pptok.lispval = lisptrue;
		  return(IDENTIFIER); }
	YY_BREAK
case 24:
# line 320 "feelflex.lex"
{ pptok.lispval = nil;
		  return(LISPNIL); }
	YY_BREAK
case 25:
# line 323 "feelflex.lex"
{ fprintf(stderr, "\n*** Illegal Character '%s' ignored\n",
			  visible(*yytext)); }
	YY_BREAK
case 26:
# line 326 "feelflex.lex"
ECHO;
	YY_BREAK

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yytext - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yytext + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yytext + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer(stacktop) )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yytext,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yytext + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yytext + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &yy_current_buffer->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yytext + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#ifdef FLEX_DEBUG
		printf( "action # %d\n", yy_act );
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer(LispObject *stacktop)

    {
    register YY_CHAR *dest = yy_current_buffer->yy_ch_buf;
    register YY_CHAR *source = yytext - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yytext;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = yy_current_buffer->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    yy_current_buffer->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    yy_current_buffer->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yytext begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yytext = &yy_current_buffer->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

static yy_state_type yy_get_previous_state()

    {
    register yy_state_type yy_current_state;
    register YY_CHAR *yy_cp;

    yy_current_state = yy_start;

    for ( yy_cp = yytext + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 170 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	}

    return ( yy_current_state );
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif

    {
    register int yy_is_jam;
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 170 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_base[yy_current_state] == 415);

    return ( yy_is_jam ? 0 : yy_current_state );
    }


#ifdef YY_USE_PROTOS
static void yyunput( YY_CHAR c, register YY_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_CHAR c;
register YY_CHAR *yy_bp;
#endif

    {
    register YY_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yytext */
    *yy_cp = yy_hold_char;

    if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_CHAR *dest =
	    &yy_current_buffer->yy_ch_buf[yy_current_buffer->yy_buf_size + 2];
	register YY_CHAR *source =
	    &yy_current_buffer->yy_ch_buf[number_to_move];

	while ( source > yy_current_buffer->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = yy_current_buffer->yy_buf_size;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yytext again */
    }


#ifdef __cplusplus
static int yyinput()
#else
static int input(LispObject *stacktop)
#endif

    {
    int c;
    YY_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yytext = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer(stacktop) )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yytext + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;

#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input(stacktop) );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yytext + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif

    {
    yy_init_buffer( yy_current_buffer, input_file );
    yy_load_buffer_state();
    }


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif

    {
    if ( yy_current_buffer == new_buffer )
	return;

    if ( yy_current_buffer )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	yy_current_buffer->yy_buf_pos = yy_c_buf_p;
	yy_current_buffer->yy_n_chars = yy_n_chars;
	}

    yy_current_buffer = new_buffer;
    yy_load_buffer_state();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif

    {
    yy_n_chars = yy_current_buffer->yy_n_chars;
    yytext = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
    yyin = yy_current_buffer->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( LispObject *stacktop, FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( stacktop, file, size )
LispObject *stacktop;
FILE *file;
int size;
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    yy_init_buffer( b, file );

    return ( b );
    }


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif

    {
    if ( b == yy_current_buffer )
	yy_current_buffer = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
# line 326 "feelflex.lex"


/* +#o123 or -#o123 or #o123 or binary or hex */
static long convert_integer OF ((char *text, int base),
(text, base),
char *text;
int base;)
{
  switch (*text) {
  case '+':
    return strtol(text + 3, 0, base);
  case '-':
    return -strtol(text + 3, 0, base);
  default:
    return strtol(text + 2, 0, base);
  }
}

/* +#5r123 or -#5r123 or #5r123 */
static long int_with_base OF ((char *text, int *ret),
(text, ret),
char *text;
int *ret;)
{
  char *val;
  int base;
  long value;

  switch (*text) {
  case '+':
    base = (int)strtol(text + 2, &val, 10);
    value = strtol(val + 1, &val, base);
    break;
  case '-':
    base = (int)strtol(text + 2, &val, 10);
    value = -strtol(val + 1, &val, base);
    break;
  default:
    base = (int)strtol(text + 1, &val, 10);
    value = strtol(val + 1, &val, base);
    break;
  }

  /* all characters used? */
  *ret = (val - text)/sizeof(char);

  return value;
}

/* 123 or #o123 or #5r123 */
static long convert_unumber OF ((char *text),
(text),
char *text;)
{
  char *val;
  int base;

  if (*text == '#')
    switch (text[1]) {
    case 'b':
    case 'B':
      return convert_integer(text, 2);
    case 'o':
    case 'O':
      return convert_integer(text, 8);
    case 'x':
    case 'X':
      return convert_integer(text, 16);
    default:
      base = (int)strtol(text + 1, &val, 10);
      return strtol(val + 1, 0, base);
    }

  return atol(text);
}

/* +num/num or -num/num or num/num */
static void convert_rational(
#ifdef __STDC__
void
#endif
)
{
  char *text = yytext;
  int sign;

  if (*text == '+') {
    sign = 1;
    text++;
  }
  else if (*text == '-') {
    sign = -1;
    text++;
  }
  else {
    sign = 1;
  }

  flex_ratnumval = sign*convert_unumber(text);
  text = strchr(text, '/');
  flex_ratdenval = convert_unumber(text + 1);

}

/* #\a or #\^a or #\alert or #\x1234 */
/* ASCII dependent */
static char convert_character(
#ifdef __STDC__
void
#endif
)
{
  register int i;
  for(i=0;i<yyleng;i++)
    if (yytext[i]=='\n') lex_input_line_number++;

  if (yyleng > 3) {		/* #\^a, #\alert, #\x1234 */
    switch (yytext[2]) {
    case '^':			/* #\^a */
      if ('a' <= yytext[3] && yytext[3] <= 'z')
	return toupper(yytext[3]) & 077;
      else
	return yytext[3] & 077;

    case 'a':			/* alert 07 */
    case 'A':
      return 07;		/* Stardent is non-ansi here */

    case 'b':			/* backspace 010 */
    case 'B':
      return '\b';

    case 'd':			/* delete 0177 */
    case 'D':
      return 0177;

    case 'f':			/* formfeed 014 */
    case 'F':
      return '\f';

    case 'l':			/* linefeed 012 */
    case 'L':
    case 'n':                   /* newline 012 */
    case 'N':
      return '\n';

    case 'r':			/* return 015 */
    case 'R':
      return '\r';

    case 't':			/* tab 011 */
    case 'T':
      return '\t';

    case 's':			/* space 040 */
    case 'S':
      return ' ';

    case 'v':			/* vertical-tab 013 */
    case 'V':
      return '\v';

    case 'x':
    case 'X':
      return (char)strtol(&yytext[3],NULL,16);
    }
  }  
  return yytext[2];
}

/* get all the escapes out of the identifier: produce the internal form */
static void tidy_id(
#ifdef __STDC__
void
#endif
)
{
  int escaped = 0;
  int i, j;

  for (i = 0; yytext[i]; i++)
    if (yytext[i] == '|' ||
	yytext[i] == '\\') {
      escaped = 1;
      break;
    }
    
  if (!escaped) {
    strcpy(flex_idval, yytext);
    return;
  }

  i = 0;
  j = 0;
  while (yytext[j]) {
    if (yytext[j] == '\\') {
      if (yytext[j+1] == '|') {
        flex_idval[i++] = '|';
        j++;
      }
      else if (yytext[j+1] == '\\') {
        flex_idval[i++] = '\\';
        j++;
      }
      else if (yytext[j+1] == '\n') {
	lex_input_line_number++;
	flex_idval[i++] = '\n';
	j++;
      }
      j++;
    } else if (yytext[j] == '|') j++;
    else {			/* Copy the text, checking for newline */
      if ((flex_idval[i++] = yytext[j++])=='\n')
	lex_input_line_number++;
    }
  }

  flex_idval[i] = 0;
}

/* do we need to escape this id when printing?
 * yes if (1) it contains a dodgy character
 *        (2) it is the id of zero length
 *        (3) it starts with the syntax of a number
 *
 * ASCII dependent
 */
int escaped_id OF ((char *id),
(id),
char *id;)
{
  int i;

  for (i = 0; id[i]; i++)
    if (id[i] < 32 || id[i] > 126 || id[i] == '|' || id[i] == '\\') return 1;

  if (strpbrk(id, "|\\#()\"',;` ") ||
      id[0] == 0 ||		/* zero length id */
      isdigit(id[0]) ||					/* 123 */
      (id[0] == '.' && !id[1]) ||			/* |.| */
      (id[0] == '.' && id[1] && isdigit(id[1])) ||	/* .123 */
      ((id[0] == '+' || id[0] == '-') &&
	id[1] && (isdigit(id[1]) ||			/* +123 */
	          (id[1] == '.' && id[2] && isdigit(id[2]))))) /* +.123 */
    return 1;
  else
    return 0;
}

static void convert_string(
#ifdef __STDC__
LispObject *stacktop
#endif
)
{
  int ch, prevch;
  int i;

  i = 0;
  while ((ch = input(stacktop)) != '"') {
    if (ch == '\\')
      switch (ch = input(stacktop)) {
      case '"':
      case '\\':
	flex_stringval[i++] = ch;
	break;

      case 'a':			/* alert */
      case 'A':
	flex_stringval[i++] = 07;
        break;

      case 'b':			/* backspace */
      case 'B':
	flex_stringval[i++] = '\b';
        break;
	
      case 'd':			/* delete */
      case 'D':
	flex_stringval[i++] = 0177;
        break;

      case 'f':			/* formfeed */
      case 'F':
	flex_stringval[i++] = '\f';
        break;

      case 'l':			/* linefeed */
      case 'L':
      case 'n':			/* newline */
      case 'N':
	flex_stringval[i++] = '\n';
	break;

      case 'r':			/* return */
      case 'R':
	flex_stringval[i++] = '\r';
        break;

      case 't':			/* tab */
      case 'T':
	flex_stringval[i++] = '\t';
        break;

      case 'v':			/* vertical tab */
      case 'V':
	flex_stringval[i++] = '\v';
        break;

      case 'x':
      case 'X':
	prevch = ch;
	if (isxdigit(ch = input(stacktop))) {
	  char val = 0;
	  int count;
	  for (count = 0; count < 4 && isxdigit(ch); count++, ch = input(stacktop)) {
	    val = 16*val;
	    if (isupper(ch)) val += ch - 'A' + 10;
	    else if (islower(ch)) val += ch - 'a' + 10;
	    else val += ch - '0';
	  }
	  flex_stringval[i++] = val;
	}
	else flex_stringval[i++] = prevch;
	unput(ch);
	break;

      default:
	flex_stringval[i++] = ch;
	break;
      }
    else flex_stringval[i++] = ch;
    if (ch == '\n') lex_input_line_number++;
  }

  flex_stringval[i] = 0;

}

static double convert_float(
#ifdef __STDC__
void
#endif
)
{
#ifndef atof
#ifdef __ANSI__
  extern double atof(char *);
#else
  extern double atof();
#endif
#endif

  char buf[256];
  int i;

  for (i = 0; yytext[i]; i++)
    buf[i] = (yytext[i] == 'd' || yytext[i] == 'D') ? 'E' : yytext[i];
  buf[i] = 0;

  return atof(buf);
}

/* more ASCII dependence */
char *visible OF ((char ch),
(ch),
char ch;)
{
  static char buf[10];
  char *ptr = buf;

  if (ch == 127) return "^?";

  if (ch > 127) {
    *ptr++ = 'M';
    *ptr++ = '-';
    ch = ch & 0x7f;
  }

  if (ch < 32) {
    *ptr++ = '^';
    ch += '@';
  }

  *ptr++ = ch;
  *ptr = 0;

  return buf;
}

#ifdef WITH_FUDGE
#include "yyfudge.c"
#endif
